# Generated by Django 5.2.7 on 2025-10-22 06:43

import django.db.models.deletion
import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='course_image/default.jpg', null=True, upload_to='course_image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thumbnail', embed_video.fields.EmbedVideoField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='category', to='instructor.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
