# Generated by Django 5.2.7 on 2025-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Course',
            new_name='course',
        ),
    ]
