# Generated by Django 5.2.7 on 2025-10-23 06:41

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_rename_course_module_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('order', models.IntegerField()),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='instructor.module')),
            ],
        ),
    ]
